export interface Language {
  code: string
  name: string
  nativeName: string
  flag: string
}

export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'ig', name: 'Igbo', nativeName: 'Igbo', flag: '🇳🇬' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', flag: '🇳🇬' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', flag: '🇿🇦' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' }
]

export const translations = {
  en: {
    // App branding
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'Church Management System',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'Building systems that serves God\'s kingdom',
    'bible.verse': 'Matthew 6:33',
    'bible.text': 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.',
    
    // Authentication
    'auth.login': 'Sign In',
    'auth.logout': 'Sign Out',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.signin_subtitle': 'Sign in to your church account',
    'auth.loading': 'Signing in...',
    'auth.error.invalid': 'Invalid email or password',
    'auth.error.network': 'Network error. Please try again.',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.users': 'Users',
    'nav.attendance': 'Attendance',
    'nav.tasks': 'Tasks',
    'nav.folders': 'Folders',
    'nav.reports': 'Reports',
    'nav.programs': 'Programs',
    'nav.souls_won': 'Souls Won',
    'nav.follow_ups': 'Follow-ups',
    'nav.notices': 'Notices',
    'nav.excuses': 'Excuses',
    'nav.settings': 'Settings',
    'nav.profile': 'My Profile',
    'nav.subscription': 'Subscription',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'Here\'s your church management overview',
    'dashboard.stats.attendance': 'Today\'s Attendance',
    'dashboard.stats.tasks': 'Pending Tasks',
    'dashboard.stats.notices': 'Active Notices',
    'dashboard.stats.souls': 'Souls Won This Month',
    'dashboard.stats.newcomers': 'New Visitors',
    'dashboard.stats.programs': 'Active Programs',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.language': 'Language',
    
    // Roles
    'role.pastor': 'Pastor',
    'role.worker': 'Worker',
    'role.member': 'Member',
    'role.newcomer': 'Newcomer',
    
    // Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.completed': 'Completed',
    'status.present': 'Present',
    'status.absent': 'Absent',
    'status.excused': 'Excused',
    
    // Forms
    'form.full_name': 'Full Name',
    'form.email': 'Email Address',
    'form.phone': 'Phone Number',
    'form.address': 'Address',
    'form.role': 'Role',
    'form.department': 'Department',
    'form.date': 'Date',
    'form.time': 'Time',
    'form.notes': 'Notes',
    'form.description': 'Description',
    'form.title': 'Title',
    'form.content': 'Content',
    'form.priority': 'Priority',
    'form.due_date': 'Due Date',
    'form.status': 'Status',
    
    // Messages
    'message.saved': 'Saved successfully',
    'message.deleted': 'Deleted successfully',
    'message.updated': 'Updated successfully',
    'message.created': 'Created successfully',
    'message.error': 'An error occurred',
    'message.no_data': 'No data available',
    'message.confirm_delete': 'Are you sure you want to delete this item?',
    
    // Footer
    'footer.copyright': '© 2025 The AMEN TECH. All rights reserved.',
    'footer.verse': 'Matthew 6:33'
  },
  
  de: {
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'Kirchenverwaltungssystem',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'Systeme bauen, die Gottes Reich dienen',
    'bible.verse': 'Matthäus 6:33',
    'auth.login': 'Anmelden',
    'auth.logout': 'Abmelden',
    'auth.email': 'E-Mail-Adresse',
    'auth.password': 'Passwort',
    'auth.signin_subtitle': 'Melden Sie sich in Ihrem Kirchenkonto an',
    'nav.dashboard': 'Dashboard',
    'nav.users': 'Benutzer',
    'nav.attendance': 'Anwesenheit',
    'nav.tasks': 'Aufgaben',
    'nav.folders': 'Ordner',
    'nav.reports': 'Berichte',
    'nav.programs': 'Programme',
    'nav.souls_won': 'Gewonnene Seelen',
    'nav.follow_ups': 'Nachverfolgung',
    'nav.notices': 'Mitteilungen',
    'nav.excuses': 'Entschuldigungen',
    'nav.settings': 'Einstellungen',
    'nav.profile': 'Mein Profil',
    'dashboard.welcome': 'Willkommen zurück',
    'dashboard.overview': 'Hier ist Ihre Kirchenverwaltungsübersicht',
    'role.pastor': 'Pastor',
    'role.worker': 'Mitarbeiter',
    'role.member': 'Mitglied',
    'role.newcomer': 'Neuankömmling',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.add': 'Hinzufügen',
    'common.create': 'Erstellen',
    'common.update': 'Aktualisieren',
    'common.submit': 'Einreichen',
    'common.loading': 'Laden...',
    'common.language': 'Sprache',
    'footer.copyright': '© 2025 The AMEN TECH. Alle Rechte vorbehalten.',
    'footer.verse': 'Matthäus 6:33'
  },
  
  fr: {
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'Système de Gestion d\'Église',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'Construire des systèmes qui servent le royaume de Dieu',
    'bible.verse': 'Matthieu 6:33',
    'auth.login': 'Se connecter',
    'auth.logout': 'Se déconnecter',
    'auth.email': 'Adresse e-mail',
    'auth.password': 'Mot de passe',
    'auth.signin_subtitle': 'Connectez-vous à votre compte d\'église',
    'nav.dashboard': 'Tableau de bord',
    'nav.users': 'Utilisateurs',
    'nav.attendance': 'Présence',
    'nav.tasks': 'Tâches',
    'nav.folders': 'Dossiers',
    'nav.reports': 'Rapports',
    'nav.programs': 'Programmes',
    'nav.souls_won': 'Âmes gagnées',
    'nav.follow_ups': 'Suivi',
    'nav.notices': 'Avis',
    'nav.excuses': 'Excuses',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Mon profil',
    'dashboard.welcome': 'Bon retour',
    'dashboard.overview': 'Voici votre aperçu de gestion d\'église',
    'role.pastor': 'Pasteur',
    'role.worker': 'Travailleur',
    'role.member': 'Membre',
    'role.newcomer': 'Nouveau venu',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.add': 'Ajouter',
    'common.create': 'Créer',
    'common.update': 'Mettre à jour',
    'common.submit': 'Soumettre',
    'common.loading': 'Chargement...',
    'common.language': 'Langue',
    'footer.copyright': '© 2025 The AMEN TECH. Tous droits réservés.',
    'footer.verse': 'Matthieu 6:33'
  },
  
  es: {
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'Sistema de Gestión de Iglesia',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'Construyendo sistemas que sirven al reino de Dios',
    'bible.verse': 'Mateo 6:33',
    'auth.login': 'Iniciar sesión',
    'auth.logout': 'Cerrar sesión',
    'auth.email': 'Dirección de correo',
    'auth.password': 'Contraseña',
    'auth.signin_subtitle': 'Inicia sesión en tu cuenta de iglesia',
    'nav.dashboard': 'Panel',
    'nav.users': 'Usuarios',
    'nav.attendance': 'Asistencia',
    'nav.tasks': 'Tareas',
    'nav.folders': 'Carpetas',
    'nav.reports': 'Informes',
    'nav.programs': 'Programas',
    'nav.souls_won': 'Almas ganadas',
    'nav.follow_ups': 'Seguimientos',
    'nav.notices': 'Avisos',
    'nav.excuses': 'Excusas',
    'nav.settings': 'Configuración',
    'nav.profile': 'Mi perfil',
    'dashboard.welcome': 'Bienvenido de vuelta',
    'dashboard.overview': 'Aquí está tu resumen de gestión de iglesia',
    'role.pastor': 'Pastor',
    'role.worker': 'Trabajador',
    'role.member': 'Miembro',
    'role.newcomer': 'Recién llegado',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.create': 'Crear',
    'common.update': 'Actualizar',
    'common.submit': 'Enviar',
    'common.loading': 'Cargando...',
    'common.language': 'Idioma',
    'footer.copyright': '© 2025 The AMEN TECH. Todos los derechos reservados.',
    'footer.verse': 'Mateo 6:33'
  },
  
  pt: {
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'Sistema de Gestão de Igreja',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'Construindo sistemas que servem ao reino de Deus',
    'bible.verse': 'Mateus 6:33',
    'auth.login': 'Entrar',
    'auth.logout': 'Sair',
    'auth.email': 'Endereço de e-mail',
    'auth.password': 'Senha',
    'auth.signin_subtitle': 'Entre na sua conta da igreja',
    'nav.dashboard': 'Painel',
    'nav.users': 'Usuários',
    'nav.attendance': 'Presença',
    'nav.tasks': 'Tarefas',
    'nav.folders': 'Pastas',
    'nav.reports': 'Relatórios',
    'nav.programs': 'Programas',
    'nav.souls_won': 'Almas ganhas',
    'nav.follow_ups': 'Acompanhamentos',
    'nav.notices': 'Avisos',
    'nav.excuses': 'Desculpas',
    'nav.settings': 'Configurações',
    'nav.profile': 'Meu perfil',
    'dashboard.welcome': 'Bem-vindo de volta',
    'dashboard.overview': 'Aqui está sua visão geral de gestão da igreja',
    'role.pastor': 'Pastor',
    'role.worker': 'Trabalhador',
    'role.member': 'Membro',
    'role.newcomer': 'Recém-chegado',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.add': 'Adicionar',
    'common.create': 'Criar',
    'common.update': 'Atualizar',
    'common.submit': 'Enviar',
    'common.loading': 'Carregando...',
    'common.language': 'Idioma',
    'footer.copyright': '© 2025 The AMEN TECH. Todos os direitos reservados.',
    'footer.verse': 'Mateus 6:33'
  },
  
  sw: {
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'Mfumo wa Usimamizi wa Kanisa',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'Kujenga mifumo inayotumikia ufalme wa Mungu',
    'bible.verse': 'Mathayo 6:33',
    'auth.login': 'Ingia',
    'auth.logout': 'Toka',
    'auth.email': 'Anwani ya barua pepe',
    'auth.password': 'Nenosiri',
    'auth.signin_subtitle': 'Ingia kwenye akaunti yako ya kanisa',
    'nav.dashboard': 'Dashibodi',
    'nav.users': 'Watumiaji',
    'nav.attendance': 'Mahudhurio',
    'nav.tasks': 'Kazi',
    'nav.folders': 'Folda',
    'nav.reports': 'Ripoti',
    'nav.programs': 'Programu',
    'nav.souls_won': 'Roho zilizoshindwa',
    'nav.follow_ups': 'Ufuatiliaji',
    'nav.notices': 'Arifa',
    'nav.excuses': 'Udhuru',
    'nav.settings': 'Mipangilio',
    'nav.profile': 'Wasifu wangu',
    'dashboard.welcome': 'Karibu tena',
    'dashboard.overview': 'Hii ni muhtasari wako wa usimamizi wa kanisa',
    'role.pastor': 'Mchungaji',
    'role.worker': 'Mfanyakazi',
    'role.member': 'Mwanachama',
    'role.newcomer': 'Mgeni mpya',
    'common.save': 'Hifadhi',
    'common.cancel': 'Ghairi',
    'common.delete': 'Futa',
    'common.edit': 'Hariri',
    'common.add': 'Ongeza',
    'common.create': 'Unda',
    'common.update': 'Sasisha',
    'common.submit': 'Wasilisha',
    'common.loading': 'Inapakia...',
    'common.language': 'Lugha',
    'footer.copyright': '© 2025 The AMEN TECH. Haki zote zimehifadhiwa.',
    'footer.verse': 'Mathayo 6:33'
  },
  
  ig: {
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'Usoro Njikwa Ụka',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'Na-ewu usoro na-eje ozi alaeze Chineke',
    'bible.verse': 'Matiu 6:33',
    'auth.login': 'Banye',
    'auth.logout': 'Pụọ',
    'auth.email': 'Adreesị email',
    'auth.password': 'Okwuntughe',
    'auth.signin_subtitle': 'Banye n\'akaụntụ ụka gị',
    'nav.dashboard': 'Dashibọọdụ',
    'nav.users': 'Ndị ọrụ',
    'nav.attendance': 'Ọbịbịa',
    'nav.tasks': 'Ọrụ',
    'nav.folders': 'Folda',
    'nav.reports': 'Akụkọ',
    'nav.programs': 'Mmemme',
    'nav.souls_won': 'Mkpụrụ obi e nwetara',
    'nav.follow_ups': 'Nsochi',
    'nav.notices': 'Ọkwa',
    'nav.excuses': 'Mgbaghara',
    'nav.settings': 'Nhazi',
    'nav.profile': 'Profaịlụ m',
    'dashboard.welcome': 'Nnọọ ọzọ',
    'dashboard.overview': 'Nke a bụ nchịkọta njikwa ụka gị',
    'role.pastor': 'Onye ụkọchukwu',
    'role.worker': 'Onye ọrụ',
    'role.member': 'Onye otu',
    'role.newcomer': 'Onye ọbịa ọhụrụ',
    'common.save': 'Chekwaa',
    'common.cancel': 'Kagbuo',
    'common.delete': 'Hichapụ',
    'common.edit': 'Dezie',
    'common.add': 'Tinye',
    'common.create': 'Kee',
    'common.update': 'Melite',
    'common.submit': 'Ziga',
    'common.loading': 'Na-ebu...',
    'common.language': 'Asụsụ',
    'footer.copyright': '© 2025 The AMEN TECH. Ikike niile echekwara.',
    'footer.verse': 'Matiu 6:33'
  },
  
  yo: {
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'Eto Iṣakoso Ijo',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'Kikọ awọn eto ti o ṣiṣẹ fun ijọba Ọlọrun',
    'bible.verse': 'Matiu 6:33',
    'auth.login': 'Wọle',
    'auth.logout': 'Jade',
    'auth.email': 'Adirẹsi imeeli',
    'auth.password': 'Ọrọ igbaniwọle',
    'auth.signin_subtitle': 'Wọle si akọọlẹ ijo rẹ',
    'nav.dashboard': 'Dashibọọdu',
    'nav.users': 'Awọn olumulo',
    'nav.attendance': 'Wiwa',
    'nav.tasks': 'Awọn iṣẹ',
    'nav.folders': 'Awọn folda',
    'nav.reports': 'Awọn ijabọ',
    'nav.programs': 'Awọn eto',
    'nav.souls_won': 'Awọn ọkàn ti a gba',
    'nav.follow_ups': 'Atẹle',
    'nav.notices': 'Awọn ikede',
    'nav.excuses': 'Awọn idariji',
    'nav.settings': 'Awọn eto',
    'nav.profile': 'Profaili mi',
    'dashboard.welcome': 'Kaabo pada',
    'dashboard.overview': 'Eyi ni akopọ iṣakoso ijo rẹ',
    'role.pastor': 'Pastọ',
    'role.worker': 'Oṣiṣẹ',
    'role.member': 'Ọmọ ẹgbẹ',
    'role.newcomer': 'Alejo tuntun',
    'common.save': 'Fi pamọ',
    'common.cancel': 'Fagilee',
    'common.delete': 'Pa rẹ',
    'common.edit': 'Ṣatunkọ',
    'common.add': 'Fi kun',
    'common.create': 'Ṣẹda',
    'common.update': 'Imudojuiwọn',
    'common.submit': 'Fi silẹ',
    'common.loading': 'N gbé...',
    'common.language': 'Ede',
    'footer.copyright': '© 2025 The AMEN TECH. Gbogbo ẹtọ ni a fi pamọ.',
    'footer.verse': 'Matiu 6:33'
  },
  
  zu: {
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'Uhlelo Lokuphatha Ibandla',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'Sakha izinhlelo ezisebenzela umbuso kaNkulunkulu',
    'bible.verse': 'Mathewu 6:33',
    'auth.login': 'Ngena',
    'auth.logout': 'Phuma',
    'auth.email': 'Ikheli le-imeyili',
    'auth.password': 'Iphasiwedi',
    'auth.signin_subtitle': 'Ngena ku-akhawunti yakho yebandla',
    'nav.dashboard': 'Ideshibhodi',
    'nav.users': 'Abasebenzisi',
    'nav.attendance': 'Ukuzimela',
    'nav.tasks': 'Imisebenzi',
    'nav.folders': 'Amafolda',
    'nav.reports': 'Imibiko',
    'nav.programs': 'Izinhlelo',
    'nav.souls_won': 'Imiphefumulo etholiwe',
    'nav.follow_ups': 'Ukulandela',
    'nav.notices': 'Izaziso',
    'nav.excuses': 'Iziscuzo',
    'nav.settings': 'Izilungiselelo',
    'nav.profile': 'Iphrofayili yami',
    'dashboard.welcome': 'Sawubona futhi',
    'dashboard.overview': 'Nansi isifinyezo sakho sokuphatha ibandla',
    'role.pastor': 'Umfundisi',
    'role.worker': 'Umsebenzi',
    'role.member': 'Ilungu',
    'role.newcomer': 'Umuntu omusha',
    'common.save': 'Londoloza',
    'common.cancel': 'Khansela',
    'common.delete': 'Susa',
    'common.edit': 'Hlela',
    'common.add': 'Engeza',
    'common.create': 'Dala',
    'common.update': 'Buyekeza',
    'common.submit': 'Thumela',
    'common.loading': 'Iyalayisha...',
    'common.language': 'Ulimi',
    'footer.copyright': '© 2025 The AMEN TECH. Wonke amalungelo agodliwe.',
    'footer.verse': 'Mathewu 6:33'
  },
  
  ar: {
    'app.title': 'The AMEN TECH',
    'app.subtitle': 'نظام إدارة الكنيسة',
    'company.name': 'The AMEN TECH',
    'company.tagline': 'بناء أنظمة تخدم ملكوت الله',
    'bible.verse': 'متى 6:33',
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'عنوان البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.signin_subtitle': 'سجل الدخول إلى حساب الكنيسة الخاص بك',
    'nav.dashboard': 'لوحة التحكم',
    'nav.users': 'المستخدمون',
    'nav.attendance': 'الحضور',
    'nav.tasks': 'المهام',
    'nav.folders': 'المجلدات',
    'nav.reports': 'التقارير',
    'nav.programs': 'البرامج',
    'nav.souls_won': 'النفوس المكسوبة',
    'nav.follow_ups': 'المتابعات',
    'nav.notices': 'الإشعارات',
    'nav.excuses': 'الأعذار',
    'nav.settings': 'الإعدادات',
    'nav.profile': 'ملفي الشخصي',
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.overview': 'هذه نظرة عامة على إدارة الكنيسة الخاصة بك',
    'role.pastor': 'القس',
    'role.worker': 'العامل',
    'role.member': 'العضو',
    'role.newcomer': 'الوافد الجديد',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تحرير',
    'common.add': 'إضافة',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.submit': 'إرسال',
    'common.loading': 'جاري التحميل...',
    'common.language': 'اللغة',
    'footer.copyright': '© 2025 The AMEN TECH. جميع الحقوق محفوظة.',
    'footer.verse': 'متى 6:33'
  }
}

export function getTranslation(key: string, language: string = 'en'): string {
  const langTranslations = translations[language as keyof typeof translations] || translations.en
  return langTranslations[key as keyof typeof langTranslations] || key
}